FROM docker.wso2.com/nginx

COPY pattern-11/nginx/broker.wso2.com.conf /etc/nginx/conf.d/
COPY pattern-11/nginx/analytics.wso2.com.conf /etc/nginx/conf.d/
COPY pattern-11/nginx/integrator.wso2.com.conf /etc/nginx/conf.d/
COPY pattern-11/nginx/business-process.wso2.com.conf /etc/nginx/conf.d/

COPY pattern-11/nginx/certs /etc/nginx/ssl/
