FROM docker.wso2.com/nginx

COPY pattern-10/nginx/broker.wso2.com.conf /etc/nginx/conf.d/
COPY pattern-10/nginx/analytics.wso2.com.conf /etc/nginx/conf.d/
COPY pattern-10/nginx/integrator.wso2.com.conf /etc/nginx/conf.d/

COPY pattern-10/nginx/certs /etc/nginx/ssl/
