FROM docker.wso2.com/nginx

COPY pattern-6/nginx/integrator.wso2.com.conf /etc/nginx/conf.d/
COPY pattern-6/nginx/analytics.wso2.com.conf /etc/nginx/conf.d/

COPY pattern-6/nginx/certs /etc/nginx/ssl/
